# Generated by Django 2.0.2 on 2018-02-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('wind_direction', models.CharField(max_length=30)),
                ('wind_speed', models.TextField(max_length=10)),
                ('astronomy', models.CharField(max_length=30)),
                ('time', models.TextField(max_length=10)),
                ('temp', models.CharField(max_length=30)),
            ],
        ),
    ]
