# Generated by Django 2.0.2 on 2018-03-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_data',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
