# Generated by Django 2.0 on 2018-03-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analy', '0002_weather_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_data',
            name='humidity',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='weather_data',
            name='presure',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='weather_data',
            name='visibility',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
