# Generated by Django 2.0 on 2018-04-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analy', '0003_auto_20180326_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='pre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(max_length=30)),
                ('date', models.IntegerField(default='', max_length=30)),
                ('wind', models.TextField(max_length=30)),
            ],
        ),
    ]
