# Generated by Django 2.0 on 2018-04-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analy', '0004_pre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre',
            name='temp',
            field=models.TextField(max_length=30),
        ),
    ]
