# Generated by Django 2.0 on 2018-04-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analy', '0005_auto_20180412_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre',
            name='date',
            field=models.TextField(default='', max_length=30),
        ),
    ]
